// src/features/supplies/components/AddSupplyForm.tsx
import { useState } from 'react';
import type {
  CreateMedicalSupplyDTO,
  //   UnitType,
  //   CategoryType,
} from '../../../types/medical-supply';
import { useMedicalSupplyStore } from '../../../stores/medical-supply';

interface AddSupplyFormProps {
  onComplete: () => void;
}

const AddSupplyForm = ({ onComplete }: AddSupplyFormProps) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const addSupply = useMedicalSupplyStore((state) => state.addSupply);

  const [formData, setFormData] = useState<CreateMedicalSupplyDTO>({
    name: '',
    category: 'obat',
    unit: 'tablet',
    stock: 0,
    minimumStock: 0,
    price: 0,
    description: '',
    code: '', // Will be generated by the store
  });

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
    >
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]:
        name === 'stock' || name === 'minimumStock' || name === 'price'
          ? parseInt(value)
          : value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      setIsSubmitting(true);
      await addSupply(formData);
      onComplete();
    } catch (error) {
      console.error('Error adding supply:', error);
      alert('Terjadi kesalahan saat menambahkan item');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className='max-w-2xl mx-auto'>
      <form onSubmit={handleSubmit} className='space-y-6'>
        <div className='bg-white p-6 rounded-lg shadow'>
          <h2 className='text-lg font-medium text-gray-900 mb-6'>
            Tambah Item Baru
          </h2>

          <div className='space-y-4'>
            <div>
              <label className='block text-sm font-medium text-gray-700 mb-1'>
                Nama Item
              </label>
              <input
                type='text'
                name='name'
                value={formData.name}
                onChange={handleChange}
                required
                className='w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500'
              />
            </div>

            <div className='grid grid-cols-2 gap-4'>
              <div>
                <label className='block text-sm font-medium text-gray-700 mb-1'>
                  Kategori
                </label>
                <select
                  name='category'
                  value={formData.category}
                  onChange={handleChange}
                  className='w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500'
                >
                  <option value='obat'>Obat-obatan</option>
                  <option value='supplies'>Supplies</option>
                  <option value='alat'>Alat Medis</option>
                </select>
              </div>

              <div>
                <label className='block text-sm font-medium text-gray-700 mb-1'>
                  Satuan
                </label>
                <select
                  name='unit'
                  value={formData.unit}
                  onChange={handleChange}
                  className='w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500'
                >
                  <option value='tablet'>Tablet</option>
                  <option value='strip'>Strip</option>
                  <option value='botol'>Botol</option>
                  <option value='ampul'>Ampul</option>
                  <option value='pcs'>Pcs</option>
                </select>
              </div>
            </div>

            <div className='grid grid-cols-3 gap-4'>
              <div>
                <label className='block text-sm font-medium text-gray-700 mb-1'>
                  Stok Awal
                </label>
                <input
                  type='number'
                  name='stock'
                  value={formData.stock}
                  onChange={handleChange}
                  min='0'
                  required
                  className='w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500'
                />
              </div>

              <div>
                <label className='block text-sm font-medium text-gray-700 mb-1'>
                  Stok Minimum
                </label>
                <input
                  type='number'
                  name='minimumStock'
                  value={formData.minimumStock}
                  onChange={handleChange}
                  min='0'
                  required
                  className='w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500'
                />
              </div>

              <div>
                <label className='block text-sm font-medium text-gray-700 mb-1'>
                  Harga
                </label>
                <input
                  type='number'
                  name='price'
                  value={formData.price}
                  onChange={handleChange}
                  min='0'
                  required
                  className='w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500'
                />
              </div>
            </div>

            <div>
              <label className='block text-sm font-medium text-gray-700 mb-1'>
                Deskripsi
              </label>
              <textarea
                name='description'
                value={formData.description}
                onChange={handleChange}
                rows={3}
                className='w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500'
              />
            </div>
          </div>

          <div className='mt-6 flex justify-end space-x-4'>
            <button
              type='button'
              onClick={onComplete}
              className='px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50'
            >
              Batal
            </button>
            <button
              type='submit'
              disabled={isSubmitting}
              className='px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md shadow-sm hover:bg-blue-700 disabled:opacity-50'
            >
              {isSubmitting ? 'Menyimpan...' : 'Simpan Item'}
            </button>
          </div>
        </div>
      </form>
    </div>
  );
};

export default AddSupplyForm;
